name: Android CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: gradle
        
    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v2.0.2
        
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Access KAKAO_APP_KEY
      run: |
          echo KAKAO_APP_KEY=\"$API_KEY\" >> local.properties
      shell: bash
      env:
        API_KEY: ${{ secrets.KAKAO_APP_KEY }}
      
    - name: Run ktlint
      run: ./gradlew ktlintCheck
      
    - name: Run Unit tests
      run: ./gradlew testDebugUnitTest
      
    - name: Android Test Report Action
      uses: asadmansr/android-test-report-action@v1.2.0   
      if: ${{ always() }}
      
    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace
